### ISSUE TITLE
Improve/document environment for running recorded_failures

### ISSUE THREAD

**Issue by pschanely** [mristin/python-by-contract-corpus#110]
With additions to the PYTHONPATH, simply importing some recorded_failure examples fails, e.g.:
```
$ python recorded_failures/ethz_eprog_2019/exercise_12/problem_01/invalid_regexp_for_floating_point_numbers.py
Traceback (most recent call last):
  File "/Users/pschanely/proj/python-by-contract-corpus/recorded_failures//ethz_eprog_2019/exercise_12/problem_01/invalid_regexp_for_floating_point_numbers.py", line 40, in <module>
    from correct_programs import common
ModuleNotFoundError: No module named 'correct_programs'
```

We should make this easier and/or document our expectations.

**Comment by mristin** [comment]
@pschanely do I understand you correctly: you would like to enable users to access recorded failures as proper Python modules?

**Comment by pschanely** [comment]
@mristin - yup. Tooling to detect faulty contracts will typically want to be able to import the functions (e.g. `crosshair check <module>.<fn>`, `icontract_hypothesis.test_with_inferred_strategy`).

**Comment by mristin** [comment]
@pschanely I see. I'll change the names.

Just to avoid confusion: you noticed the folder where I put the curated failures: https://github.com/mristin/python-by-contract-corpus/tree/main/python_by_contract_corpus/incorrect_from_recorded? I imagined that these modules would be checked with the tools and the bugs discovered.

Shouldn't I move the recorded failures to a folder `archive/` or give it a different name? I really kept the code only so that people can trace back how we curated them. They have actually no practical utility.

**Comment by pschanely** [comment]
> Just to avoid confusion: you noticed the folder where I put the curated failures: https://github.com/mristin/python-by-contract-corpus/tree/main/python_by_contract_corpus/incorrect_from_recorded? I imagined that these modules would be checked with the tools and the bugs discovered.

Arg, yes that's my problem! I even knew this at one point and forgot. Indeed, all the `incorrect_from_recorded` examples import.

> Shouldn't I move the recorded failures to a folder `archive/` or give it a different name? You won't be the last one to mistake them for curated failures.
> 
> I really kept the code only so that people can trace back how we curated them. They have actually no practical utility.

Sure, maybe it would be nice to hide them a little more. But the docs are pretty clear; I was just sloppy.
